# Generated by Django 3.2 on 2023-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230426_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
