# Generated by Django 4.2 on 2023-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_teacher_is_verified_alter_teacher_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='name',
        ),
    ]
