# Generated by Django 4.2 on 2023-05-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_teacher_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
