# Generated by Django 4.2 on 2023-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_teachers_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
