# Generated by Django 3.2 on 2023-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teachers_is_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='is_submit',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
