# Generated by Django 3.2 on 2023-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20230509_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
