# Generated by Django 3.2 on 2023-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_useraccount_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
