# Generated by Django 3.2 on 2023-05-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20230509_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='submitted_at',
        ),
    ]
