# Generated by Django 4.2 on 2023-06-03 04:09

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 6, 3, 4, 9, 49, tzinfo=datetime.timezone.utc)),
        ),
    ]
