# Generated by Django 4.2 on 2023-06-03 10:21

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 6, 3, 10, 21, 20, tzinfo=datetime.timezone.utc)),
        ),
    ]
