# Generated by Django 3.2 on 2023-05-09 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230509_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
