# Generated by Django 4.2 on 2023-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
