# Generated by Django 4.2 on 2023-05-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_chapter_is_completed_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
