# Generated by Django 4.2 on 2023-05-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_videoprogress_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
