# Generated by Django 4.2 on 2023-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_videoprogress_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
