# Generated by Django 4.2 on 2023-05-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banners',
        ),
    ]
