# Generated by Django 4.2 on 2023-05-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_banner_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
