# Generated by Django 4.2 on 2023-05-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
