# Generated by Django 4.2 on 2023-05-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('courses', '0019_remove_chatroom_users_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom'),
        ),
    ]
