# Generated by Django 4.2 on 2023-05-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_type',
            field=models.CharField(default='checkbox', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
