# Generated by Django 4.2 on 2023-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_quiz_answer_type_alter_quiz_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(max_length=100),
        ),
    ]
