# Generated by Django 4.2 on 2023-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_quiz_option1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
