# Generated by Django 4.2 on 2023-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_quiz_option1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
