# Generated by Django 4.2 on 2023-06-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_quiz_option2_alter_quiz_option3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='courses',
            new_name='course',
        ),
    ]
