# Generated by Django 4.2 on 2023-06-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_quizattempt_quiz_delete_quizkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
