# Generated by Django 4.2 on 2023-06-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_rename_course_id_quizattempt_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
