# Generated by Django 4.2 on 2023-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='room_code',
            field=models.IntegerField(),
        ),
    ]
